[Find offers] Add view switcher
WebUI-Project-Based-10-nr/Client pull request #191
Opened 2024-11-13 18:36 UTC by k7bart

<img width="1380" alt="Screenshot 2024-11-13 at 20 24 23" src="https://github.com/user-attachments/assets/0e9ed435-f429-4e59-8439-79f9088b30d4">

2024-11-13 19:21 UTC, Yurii-04 approved these changes

2024-11-13 19:35 UTC, Annaivv approved these changes

2024-11-14 08:35 UTC, dimaP2341 approved these changes

2024-11-14 18:34 UTC, nrevutska approved these changes

2024-11-14 18:38 UTC, nrevutska requested changes
there's problem with eslint, looks like it is regarding new code, can you investigate this problem?

2024-11-15 08:57 UTC, nrevutska approved these changes

2024-11-15 10:01 UTC, merged